### ISSUE TITLE
add python 3.x support

### ISSUE THREAD

**Issue by LordSyd** [commenthol/gdal2tiles-leaflet#16]
Sadly this does not work with python 3.x. It would be great if the script could be updated to work on new versions of python. 

```
 File "gdal2tiles-multiprocess.py", line 50
    print 'You are using "old gen" bindings. gdal2tiles needs "new gen" bindings.'
                                                                                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('You are using "old gen" bindings. gdal2tiles needs "new gen" bindings.')?
```

This is the error when I try to run it

**Comment by commenthol** [comment]
PRs are welcome...

**Comment by LordSyd** [comment]
I wish I was good enough to implement that myself - but having only 3 Months of Python experience I wouldn't even know where to start. ;) But, allas, I found another way of tiling my map using maptiler for the moment - still, would love using this script once it gets updated.

**Comment by commenthol** [comment]
@LordSyd python3 should work now.
