### ISSUE TITLE
Some tiles are missing

### ISSUE THREAD

**Issue by Slavix72** [commenthol/gdal2tiles-leaflet#25]
I use a command
$ gdal2tiles-multiprocess.py --leaflet --processes=6  raster -z 0-4 -w none karta.jpg /tiles
and tiles 0-0-0 and 1-1-0 are missing
but
$ gdal2tiles-multiprocess.py --leaflet --processes=2  raster -z 0-4 -w none karta.jpg /tiles
gives me a full set of tiles

**Comment by Slavix72** [comment]
$ gdal2tiles-multiprocess.py --leaflet --processes=6 -p raster -z 0-4 -w none karta.jpg /tiles
$ gdal2tiles-multiprocess.py --leaflet --processes=2 -p aster -z 0-4 -w none karta.jpg /tiles

**Comment by muraliselvaraj** [comment]
Is there any update on this issue?

**Comment by Slavix72** [comment]
When using 2 cores,  this bug does not occur

**Comment by muraliselvaraj** [comment]
Even with 2 cores, it takes a long time to tile a PNG image that's large in size. (i.e 300Mb and more). Also, it is getting stuck at Generating base tiles.

**Comment by realbadidas** [comment]
i had the same issue. the fix was from moving from multi processing to single processing. quite annoying, but still works.
