### ISSUE TITLE
Does it support jpg?

### ISSUE THREAD

**Issue by OlexandrPopov** [commenthol/gdal2tiles-leaflet#3]

**Comment by commenthol** [comment]
gdal2tiles itself can connect to "JPG" tiledriver. Nonetheless for generating the overview tiles I get a "Buffer to small" exception.
Anyhow you can use this script on a *NIX machine to achieve this:
```bash
#!/bin/bash
for png in `(find tiles -name "*.png")`
do
  jpg=`echo $png | sed "s/png$/jpg/"`
  echo "--- $png"
  convert $png -quality 80 $jpg
  rm $png
done
```
Remember to have [imagemagick](http://www.imagemagick.org/) installed.

**Comment by OlexandrPopov** [comment]
thank you

**Comment by answerquest** [comment]
I just did the same and now with no apparent degradation in visual quality the whole folder is so much lighter! Using slightly different commands:  
```bash
$ find -name '*.png' -print0 | xargs -0 mogrify -format jpg
$ find -name '*.png' -print0 | xargs -0 rm
```
