### ISSUE TITLE
Zoom range lower than native zoom ignored?

### ISSUE THREAD

**Issue by alexcroox** [commenthol/gdal2tiles-leaflet#4]
If I want to tile just zoom levels 0 and 1 (`-z 0-1`) it ignores my parameter and tiles 0-5.

5 being the "Native zoom of the raster".

My goal is to host this on AWS Lambda and allocate a single zoom level to each process so that I can process tiles as fast as possible through parallel computing power (low powered single core machines)

**Comment by commenthol** [comment]
"Basic Usage" of the README should provide you with the details. As workaround consider deleting the unwanted zoomlevels in the tiles dir.

**Comment by alexcroox** [comment]
It's more saving processing time since I'd be paying per second of compute time. Is there any technical reason why you can't specify individual zoom levels, or generate lower (0-1) than the "native zoom" if it was modified to do so?

**Comment by commenthol** [comment]
This project is just a slight modification of gdal2tiles. It does not change the core algorithm which first generates the base tiles, means zoom levels greater than the available pixels of the image. After this the overview tiles are generated - these are sub-sampled tiles of the image. Overview tile generation requires the base tiles first. So there is no easy way to speed up processing.
