### ISSUE TITLE
Requests for missing files when using leaflet

### ISSUE THREAD

**Issue by rotemreiss** [commenthol/gdal2tiles-leaflet#7]
Hi,

I'm using leaflet with simple crs and I used your (great!) python script to split an image of ~15k px X ~8k px to tiles.

The result of the zoom calculation was 5.9.. so I changed 0-4 to 0-6, but I'm receiving 404 on paths like "2/3/-1", "2/2/-1", "4/-1/4", why is that? where did I go wrong? what is this -1? is it something on my JS declaration?

Thanks.
Rotem

**Comment by commenthol** [comment]
Leaflet tries to load an tile which is north-west of the first tile available. This is due to the limited boundaries of your input file. So if there is no visual artefact there is nothing to worry.
