### ISSUE TITLE
gdal2tiles.py: error: no such option: -l

### ISSUE THREAD

**Issue by lwieneke** [commenthol/gdal2tiles-leaflet#8]
Great tool, unfortunately when I try to use the leaflet option 
gdal2tiles.py -l -p raster -z 0-5 -w none test.jpg tiles

it breaks with the statement

gdal2tiles.py: error: no such option: -l

same if I try the --leaflet option
Any ideas?

**Comment by lwieneke** [comment]
Forgot to mention this: if I leave out the '-l' option I can create tiles.

**Comment by commenthol** [comment]
You may have an other version of gdal2tiles installed somewhere else. 
Using python ./gdal2tiles.py -h should list the -l option.

**Comment by MCOfficer** [comment]
had the same problem, running `python gdal2tiles.py -l [...]` instead of `./gdal2tiles -l [...]` fixed it for me.
