### ISSUE TITLE
Generating base tiles getting stuck

### ISSUE THREAD

**Issue by usmanasif** [commenthol/gdal2tiles-leaflet#9]
I am trying to convert different .tiff files using this command `python /tmp/gdal2tiles-multiprocess.py blueprint.tif tiles -z 16-22 --processes=4` and having this issue, In every 10 files any random 3-4 files getting stuck at "Generating base tiles" and takes too long to process sometimes 24-48 hours. any ideas ?

**Comment by commenthol** [comment]
try using a jpg or png file.

**Comment by usmanasif** [comment]
I tried with the png it gives this raster error `Either gdal2tiles with parameter -p 'raster' or use another GIS software for georeference e.g. gdal_transform -gcp / -a_ullr / -a_srs`

**Comment by usmanasif** [comment]
can you please guide me what effect it will make ? because result was empty @commenthol

**Comment by commenthol** [comment]
Please clone repo and run createtiles.sh in test folder.

**Comment by dixitgoyal** [comment]
Please check this repository.
https://github.com/dixitgoyal/gdal2tiles

**Comment by commenthol** [comment]
@usmanasif TIF image format has a lot of different flavors. Maybe not all of them are supported by the version of gdal2tiles. PNG and JPG are image formats which have been proven to work with the software.

**Comment by commenthol** [comment]
@dixitgoyal what do you expect me to check in your repo?

**Comment by muraliselvaraj** [comment]
@commenthol I tried with PNG image it got stuck at Generating Base Tiles for many images.
